{% set name = "anaconda-cli-base" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cli_base-{{ version }}.tar.gz
  sha256: fd0ef7cf48b98e87f52bde3f632aa58a5ab600b8c11b3f0a5a663a369d8a2e10

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python
    - anaconda-client >=1.12.0
    - readchar
    - rich
    - typer

test:
  imports:
    - anaconda_cli_base
  commands:
    - python -c "from anaconda_cli_base import __version__; assert __version__ == \"{{ version }}\""
    #- pip check # anaconda-anon-usage 0.4.3 requires conda, which is not installed.
  requires:
    - pip

about:
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
  description: A base CLI entrypoint supporting Anaconda CLI plugins
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
