{% set name = "anaconda-cli-base" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/anaconda_cli_base-{{ version }}.tar.gz
  sha256: d08c31755952b0a5c267a80f229e9205d0ad8527020629ab2394e367372302d6

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python
    - anaconda-client >=1.12.0
    - readchar
    - rich
    - typer

test:
  imports:
    - anaconda_cli_base
  commands:
    - python -c "from anaconda_cli_base import __version__; assert __version__ == \"{{ version }}\""
    - pip check
  requires:
    - pip

about:
  summary: A base CLI entrypoint supporting Anaconda CLI plugins
  description: A base CLI entrypoint supporting Anaconda CLI plugins
  home: https://anaconda.cloud
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - albertdefusco
    - mattkram
